2021h2 rollback
OperationPandoraTrigger/OPT-Client-Mod pull request #101
Opened 2021-07-30 18:05 UTC by GNCLORD-MDB

- [ ] CUP Einheiten entfernen 
- [ ] neue Einheiten als OPT Version erstellen 
- [ ] Neue Handfeuerwaffen einfügen
- [ ] Kisten bestücken
- [ ] Infanterie Klassen anpassen

2021-07-30 18:07 UTC, formtapez approved these changes
löschen tut gut

2021-07-31 11:44 UTC, formtapez commented
Du hast diese beiden Ordner gelöscht:
`extras\addons\`
`extras\keys\`
Erstell die mal wieder (leer) - Die werden ja weiterhin beim Bauen gecheckt ob man was reingelegt hat.

2021-07-31 11:50 UTC, formtapez commented
Durchsuch mal die Files nach `OPT_CUP` - Da ist noch jede Menge Zeug drin.
Der Server fährt damit nicht hoch.
Oder ist es so gewollt (Als Platzhalter zum Austauschen)?
*Drängel* 🧂

2021-07-31 12:09 UTC, GNCLORD-MDB commented
Die Ordner hab ich nicht gelöscht nur die Addons darin 
Und ja das noch nicht fertig haben ich doch gesagt, da fehlen noch was.

2021-08-01 21:39 UTC, GNCLORD-MDB commented
So mit Müden Augen alles Fertig bekommen. 
Hoffe das alles geht. 
Kann dann getestet werden.

2021-08-01 22:12 UTC, formtapez requested changes
```
 0:09:42 Warning Message: No entry 'bin\config.bin/CfgVehicles.OPT_Box_NATO_WpsSpecial_AT_L1A'.
 0:09:42 Warning Message: No entry '.vehicleClass'.
 0:09:42 Warning Message: '/' is not a value
 0:09:42 Warning Message: Bad vehicle type OPT_Box_NATO_WpsSpecial_AT_L1A
 0:09:42 [CBA] (diagnostic) INFO: EnableTargetDebug is enabled.
 0:09:42 EPE manager release (0|31|0)
 0:09:42 Warning Message: mpmissions\__cur_mp.vt7\mission.sqm/Mission/Entities/Item3/Entities/Item1/Entities/Item6.type: Vehicle class OPT_Box_NATO_WpsSpecial_AT_L1A no longer exists
```

2021-08-01 22:22 UTC, formtapez approved these changes

2021-08-01 22:22 UTC, merged