Upgraded CAS weapons from 7.62mm to 12.7mm
OperationPandoraTrigger/OPT-Client-Mod pull request #110
Opened 2021-08-09 19:24 UTC by Fank

2021-08-09 22:01 UTC, GNCLORD-MDB commented
Würde ich gerne mal von Mercurat erklärt bekommen wie so nun ein Fahrzeug geschützt in einen Heli eingebaut werden darf. 
Erstmal bis Mittwoch den so stehen lassen.

2021-08-09 23:14 UTC, GNCLORD-MDB requested changes
Falsche Kanone, nicht noch die alte.

2021-08-09 23:15 UTC, GNCLORD-MDB requested changes
Falsche Kanone, nicht noch die alte.

2021-08-10 09:35 UTC, Fank commented
@GNCLORD-MDB ?

2021-08-10 10:26 UTC, Frozen-byte commented
> @GNCLORD-MDB ?

Hatte mich verklickt. Kann dieser MR gemerged werden?

2021-08-10 10:41 UTC, GNCLORD-MDB commented
Da steht noch die Flasche Kannone drin bei Hülsen auswurf und Feuerauswurf

2021-08-10 10:49 UTC, Fank commented
> Da steht noch die Flasche Kannone drin bei Hülsen auswurf und Feuerauswurf
Kannst du das übernehmen?, hab mich da noch nicht eingearbeitet.
Ich wollte es einfach mur mal austauschen um zu checken ob die Waffe überhaupt was taugt.

2021-08-10 10:51 UTC, GNCLORD-MDB commented
@formtapez 
dann mach den zu und ich übernehme das in meine PR

2021-08-10 10:52 UTC, closed without merging